### ISSUE TITLE
dudka trubka

### ISSUE THREAD

**Issue by TheAcelot** [crossfireTeam/classicbrawlv29remake#1]
Это даже ремейком не назвешь. Как и был гкод так и остался. Могли хотя бы бд сделать нормальную а не срини🇮🇱🇮🇱🇮🇱

**Comment by SavokBS** [comment]
Окей, мы постраемся сделать на SQLite3 в будущем. Сейчас лень

**Comment by TheAcelot** [comment]
Только не как в классике, где токен, ловид а остальное жсон🇮🇱🇮🇱🇮🇱

**Comment by SavokBS** [comment]
Окей, спасибо за совет!

**Comment by TheAcelot** [comment]
Когда сервак на с++ а не на пиздоне?

**Comment by root-7325** [comment]
в будущем может ¯\_(ツ)_/¯

**Comment by TheAcelot** [comment]
ключевое слово может

**Comment by SavokBS** [comment]
> Когда сервак на с++ а не на пиздоне?

Задача кроссфайр - сливать все что есть. Если сольем на с++ дудки всякие не поймут

**Comment by TheAcelot** [comment]
Глупо сливать все на гит специально для дудок, тогда моя задача будет уничтожить ваш кросструбка
