### ISSUE TITLE
чзх

### ISSUE THREAD

**Issue by tailsjs** [crossfireTeam/classicbrawlv29remake#2]
а в чем прикол ремейка

типа лол тот же гкод классика просто вы добавили пару дефолтов

**Comment by SavokBS** [comment]
я бы мог сделать намного больше, но мне лень.

**Comment by tailsjs** [comment]
так вы же назвали это ремейком.

ремейк ставится, когда ты переделываешь что-то. тут же просто можно сказать аддоны.
